default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  username: postgres
  password: postgres

development:
  <<: *default
  url: <%= "postgres://#{ENV['POSTGRES_URL'] || 'expenses-db'}/" %>
  database: <%= "#{`git symbolic-ref --short HEAD`.strip.underscore}_development" %>

test:
  <<: *default
  url: <%= "postgres://#{ENV['POSTGRES_URL'] || 'expenses-db'}/" %>
  database: <%= "#{`git symbolic-ref --short HEAD`.strip.underscore}_test" %>

