default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  username: postgres
  password: postgres

development:
  <<: *default
  url: postgres://0.0.0.0/
  database: app_development

test:
  <<: *default
  url: postgres://0.0.0.0/
  database: app_test
