# Set the number of sidekiq concurrent connections to something that Heroku will allow.
:concurrency: 10

:retry: false

:queues:
  - default
  - mailers
  - action_mailbox_routing
  - action_mailbox_incineration
  - active_storage_analysis
  - active_storage_purge
